# Generated by Django 3.2 on 2022-05-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=200)),
                ('book', models.CharField(choices=[('L', 'Libro'), ('R', 'Revistas')], default='', max_length=200)),
                ('isbn', models.CharField(default='', max_length=10)),
                ('publisher', models.CharField(default='', max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('format', models.CharField(blank=True, choices=[('D', 'Digital'), ('F', 'Libro fisico')], max_length=100, null=True)),
                ('rack_item', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
